gitGraph
    commit id: "A"
    commit id: "B"
    branch feature-1
    commit id: "C"
    commit id: "D"
    checkout main
    commit id: "E"
    merge feature-1 id: "F"
    branch feature-2
    commit id: "G"
    checkout main
    merge feature-2 id: "H"
    commit id: "I"
