mindmap
    root((Databases))
        Relational SQL
            PostgreSQL
            MySQL
            SQLite
        Document
            MongoDB
            CouchDB
        Key-Value
            Redis
            DynamoDB
        Column-Family
            Cassandra
            ScyllaDB
        Graph
            Neo4j
            Neptune
        Search
            Elasticsearch
            Meilisearch
