mindmap
    root((Compliance))
        Data Privacy
            GDPR (EU)
            CCPA (California)
            LGPD (Brazil)
        Security
            SOC 2
            ISO 27001
        Healthcare
            HIPAA
            HITECH
        Finance
            PCI-DSS
            SOX
        Industry
            FedRAMP (US Gov)
            NIST
